MERGE INTO PUBLIC.GENRE(ID, NAME)VALUES(1,'Комедия');
MERGE INTO PUBLIC.GENRE(ID, NAME)VALUES(2,'Драма');
MERGE INTO PUBLIC.GENRE(ID, NAME)VALUES(3,'Мультфильм');
MERGE INTO PUBLIC.GENRE(ID, NAME)VALUES(4,'Триллер');
MERGE INTO PUBLIC.GENRE(ID, NAME)VALUES(5,'Документальный');
MERGE INTO PUBLIC.GENRE(ID, NAME)VALUES(6,'Боевик');

MERGE INTO PUBLIC.RATING(ID, NAME)VALUES(1,'G');
MERGE INTO PUBLIC.RATING(ID, NAME)VALUES(2,'PG');
MERGE INTO PUBLIC.RATING(ID, NAME)VALUES(3,'PG-13');
MERGE INTO PUBLIC.RATING(ID, NAME)VALUES(4,'R');
MERGE INTO PUBLIC.RATING(ID, NAME)VALUES(5,'NC-17');
